feat(deploy): update deploy

diff --git a/.github/workflows/upload-html.yml b/.github/workflows/upload-html.yml
--- a/.github/workflows/upload-html.yml
+++ b/.github/workflows/upload-html.yml
@@ -108,6 +108,20 @@ jobs:
           echo "=== [Console params][github] repository_name: ${{ github.repository }} ==="
           echo "======"
 
+      - name: Check source directory
+        run: |
+          echo "Current directory: $(pwd)"
+          echo "Listing contents of source directory:"
+          ls -la ${{ inputs.source }}
+          if [ ! -d "${{ inputs.source }}" ]; then
+            echo "Error: Source directory ${{ inputs.source }} does not exist!"
+            exit 1
+          fi
+          if [ -z "$(ls -A ${{ inputs.source }})" ]; then
+            echo "Error: Source directory ${{ inputs.source }} is empty!"
+            exit 1
+          fi
+
       - name: Upload files
         uses: appleboy/scp-action@master
         with:
